/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    String passwd;
    
     void  passwordCheck(){
         passwd = txtPasswd.getText();
         if(passwd.length() >= 8){
            lblPasswd.setText("");
       }    
         else{
             lblPasswd.setText("Enter 8 digit Password.");
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminImg = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswd = new javax.swing.JPasswordField();
        lblLogError = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        btnClearLog = new javax.swing.JButton();
        btnSignLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 100, 50));

        adminImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\my icons\\admin.png")); // NOI18N
        jPanel1.add(adminImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        panel1.setBackground(new java.awt.Color(0, 153, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 30));

        txtUname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });
        panel1.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 30));

        txtPasswd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswdActionPerformed(evt);
            }
        });
        txtPasswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswdKeyTyped(evt);
            }
        });
        panel1.add(txtPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, 30));

        lblLogError.setBackground(new java.awt.Color(255, 255, 255));
        lblLogError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogError.setForeground(new java.awt.Color(255, 51, 51));
        panel1.add(lblLogError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 350, 30));

        lblPasswd.setBackground(new java.awt.Color(255, 255, 255));
        lblPasswd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPasswd.setForeground(new java.awt.Color(255, 51, 51));
        panel1.add(lblPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 190, 30));

        btnLogIn.setBackground(new java.awt.Color(0, 51, 51));
        btnLogIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\my icons\\login.png")); // NOI18N
        btnLogIn.setText("Login");
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogInMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogInMouseReleased(evt);
            }
        });
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        btnLogIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogInKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLogInKeyReleased(evt);
            }
        });
        panel1.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 40));

        btnClearLog.setBackground(new java.awt.Color(0, 51, 51));
        btnClearLog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClearLog.setForeground(new java.awt.Color(255, 255, 255));
        btnClearLog.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\my icons\\exit.png")); // NOI18N
        btnClearLog.setText("Clear");
        btnClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogActionPerformed(evt);
            }
        });
        panel1.add(btnClearLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 40));

        btnSignLog.setBackground(new java.awt.Color(0, 51, 51));
        btnSignLog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignLog.setForeground(new java.awt.Color(255, 255, 255));
        btnSignLog.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\my icons\\signup.png")); // NOI18N
        btnSignLog.setText("Sign Up");
        btnSignLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignLogActionPerformed(evt);
            }
        });
        panel1.add(btnSignLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignLogActionPerformed
        SignUp su = new SignUp();
        su.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignLogActionPerformed

     boolean verification(String uname, String passwd){
          try
        {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            
            String sql = "select * from signup where Uname = ? and Password = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1,uname);
            st.setString(2,passwd);
          ResultSet rs =  st.executeQuery();
          if(rs.next()){
              JOptionPane.showMessageDialog(this,"Login Successful.");
              HomePage hp = new HomePage();
              hp.setVisible(true);
              this.dispose();
          }
              else{
                       JOptionPane.showMessageDialog(this,"Wrong username or password!");
                      }
              
            
               
              
                  
             
          
          
         
        }
          catch(Exception e){
               e.printStackTrace();
             
          }
      return true;
    }
    
     String uname;
     
    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        
         uname = txtUname.getText();
         passwd = txtPasswd.getText();
        
        if(uname.trim().equals("") || passwd.trim().equals("") ){
            lblLogError.setText("Please, Enter username or password");
        }
        else{
        verification(uname,passwd);
         
        }
       
    
       
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogActionPerformed
        txtUname.setText("");
        txtPasswd.setText("");
        lblLogError.setText("");
    }//GEN-LAST:event_btnClearLogActionPerformed

    private void txtPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswdActionPerformed

    private void txtPasswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswdKeyPressed
       passwordCheck();
    }//GEN-LAST:event_txtPasswdKeyPressed

    private void txtPasswdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswdKeyReleased
      passwordCheck();
    }//GEN-LAST:event_txtPasswdKeyReleased

    private void txtPasswdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswdKeyTyped
       passwordCheck();
    }//GEN-LAST:event_txtPasswdKeyTyped

    private void btnLogInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogInKeyPressed
       
         
    }//GEN-LAST:event_btnLogInKeyPressed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void btnLogInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogInKeyReleased
        
          
    }//GEN-LAST:event_btnLogInKeyReleased

    private void btnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseClicked
            
  
    }//GEN-LAST:event_btnLogInMouseClicked

    private void btnLogInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseReleased
   
    }//GEN-LAST:event_btnLogInMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminImg;
    private javax.swing.JButton btnClearLog;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogError;
    private javax.swing.JLabel lblPasswd;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField txtPasswd;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
