/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author ADMIN
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecord();
    }
    
    public void getRecord(){
        try{
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            
            PreparedStatement st = con.prepareStatement("SELECT * FROM fees_details ORDER BY RAND() LIMIT 1");
            ResultSet rs = st.executeQuery();
            rs.next();
            
            txtrecieptno.setText(rs.getString("reciept_no"));
            txtModeOP.setText(rs.getString("payment_mode"));
            String PaymentMode = rs.getString("payment_mode");
          
            if(PaymentMode.equalsIgnoreCase("cash")){
               lblcheque_dd_upi.setText("-");
               txtcheque_dd_upi.setText("-");
               txtBankName.setText("-");
               
            }
            if(PaymentMode.equalsIgnoreCase("cheque")){
               lblcheque_dd_upi.setText("cheque_no");
               txtcheque_dd_upi.setText(rs.getString("cheque_no"));
               txtBankName.setText(rs.getString("bank_name"));
               
            }
             if(PaymentMode.equalsIgnoreCase("dd")){
               lblcheque_dd_upi.setText("dd_no");
               txtcheque_dd_upi.setText(rs.getString("dd_no"));
               txtBankName.setText(rs.getString("bank_name"));
               
            }
              if(PaymentMode.equalsIgnoreCase("upi")){
               lblcheque_dd_upi.setText("upi_no");
               txtcheque_dd_upi.setText(rs.getString("upi_no"));
               txtBankName.setText(rs.getString("bank_name"));
               
            }
              
              txtRecieverName.setText(rs.getString("student_name"));
              txtyr1.setText(rs.getString("year1"));
                 txtyr2.setText(rs.getString("year2"));
                txtdate.setText(rs.getString("date"));
                txtgstin.setText(rs.getString("gstin"));
                
                txtAmount.setText(rs.getString("amount"));
                txtcgst.setText(rs.getString("cgst"));
                 txtsgst.setText(rs.getString("sgst"));
                 txtTotal.setText(rs.getString("total_amount"));
                 txtCourseName.setText(rs.getString("course_name"));
                 txtTotalWords.setText(rs.getString("total_in_words"));
                 txtRemark.setText(rs.getString("remark"));
            
        }
        catch(Exception e){
            
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        homepanel = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        lblsearch = new javax.swing.JLabel();
        editcoursepanel = new javax.swing.JPanel();
        lbleditCourse = new javax.swing.JLabel();
        courselistpanel = new javax.swing.JPanel();
        lblcourseList = new javax.swing.JLabel();
        printpanel = new javax.swing.JPanel();
        btnprint = new javax.swing.JLabel();
        editpanel = new javax.swing.JPanel();
        btnedit = new javax.swing.JLabel();
        logoutpanel = new javax.swing.JPanel();
        lbllogout = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        lblback = new javax.swing.JLabel();
        panelprint = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        lblRecieptNo = new javax.swing.JLabel();
        lblcheque_dd_upi = new javax.swing.JLabel();
        lblModeOP = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblRecieverName = new javax.swing.JLabel();
        txtrecieptno = new javax.swing.JLabel();
        txtModeOP = new javax.swing.JLabel();
        txtcheque_dd_upi = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtgstin = new javax.swing.JLabel();
        txtyr1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtyr2 = new javax.swing.JLabel();
        txtBankName = new javax.swing.JLabel();
        txtRecieverName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsrNo = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JLabel();
        txtAmount = new javax.swing.JLabel();
        txtcgst = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTotalWords = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtRemark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 51, 51));
        panel1.setMinimumSize(new java.awt.Dimension(270, 400));
        panel1.setPreferredSize(new java.awt.Dimension(270, 400));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homepanel.setBackground(new java.awt.Color(0, 51, 51));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblhome.setForeground(new java.awt.Color(255, 255, 255));
        lblhome.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\home.png")); // NOI18N
        lblhome.setText("Home");
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhomeMouseExited(evt);
            }
        });
        homepanel.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        panel1.add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 70));

        searchpanel.setBackground(new java.awt.Color(0, 51, 51));
        searchpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsearch.setForeground(new java.awt.Color(255, 255, 255));
        lblsearch.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\search2.png")); // NOI18N
        lblsearch.setText("Search Record");
        lblsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsearchMouseExited(evt);
            }
        });
        searchpanel.add(lblsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        panel1.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 80));

        editcoursepanel.setBackground(new java.awt.Color(0, 51, 51));
        editcoursepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        editcoursepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbleditCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbleditCourse.setForeground(new java.awt.Color(255, 255, 255));
        lbleditCourse.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\edit2.png")); // NOI18N
        lbleditCourse.setText("Edit Course");
        lbleditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseExited(evt);
            }
        });
        editcoursepanel.add(lbleditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.add(editcoursepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 180, 80));

        courselistpanel.setBackground(new java.awt.Color(0, 51, 51));
        courselistpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        courselistpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcourseList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcourseList.setForeground(new java.awt.Color(255, 255, 255));
        lblcourseList.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\view all record_1.png")); // NOI18N
        lblcourseList.setText("View Record");
        lblcourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcourseListMouseExited(evt);
            }
        });
        courselistpanel.add(lblcourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        panel1.add(courselistpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 80));

        printpanel.setBackground(new java.awt.Color(0, 51, 51));
        printpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        printpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnprint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\printer-.png")); // NOI18N
        btnprint.setText("Print");
        btnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnprintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnprintMouseExited(evt);
            }
        });
        printpanel.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        panel1.add(printpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 150, 70));

        editpanel.setBackground(new java.awt.Color(0, 51, 51));
        editpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        editpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\edit2.png")); // NOI18N
        btnedit.setText("Update Fees");
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
        });
        editpanel.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 70));

        panel1.add(editpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 170, 80));

        logoutpanel.setBackground(new java.awt.Color(0, 51, 51));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\exit.png")); // NOI18N
        lbllogout.setText("Logout");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });
        logoutpanel.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        panel1.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 110, 40));

        backpanel.setBackground(new java.awt.Color(0, 51, 51));
        backpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        backpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblback.setForeground(new java.awt.Color(255, 255, 255));
        lblback.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\back1.png")); // NOI18N
        lblback.setText("Back");
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbackMouseExited(evt);
            }
        });
        backpanel.add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        panel1.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 110, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 750));

        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Bharati Vidyapeeth's");
        panelprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 170, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Institute of Management and Rural Development Administration");
        panelprint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 410, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Rajwada Chock, Police station near, Sangli- 416 416");
        panelprint.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 320, -1));

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setPreferredSize(new java.awt.Dimension(100, 6));
        panelprint.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 720, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\imrd.png")); // NOI18N
        panelprint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 100, 80));

        lblRecieptNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecieptNo.setForeground(new java.awt.Color(51, 0, 102));
        lblRecieptNo.setText("Reciept No:");
        panelprint.add(lblRecieptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, 80, 20));

        lblcheque_dd_upi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcheque_dd_upi.setForeground(new java.awt.Color(51, 0, 102));
        lblcheque_dd_upi.setText("Cheque_dd_upi");
        panelprint.add(lblcheque_dd_upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 20));

        lblModeOP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModeOP.setForeground(new java.awt.Color(51, 0, 102));
        lblModeOP.setText("Mode of Payment");
        panelprint.add(lblModeOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 20));

        lblBankName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBankName.setForeground(new java.awt.Color(51, 0, 102));
        lblBankName.setText("Bank Name:");
        panelprint.add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 20));

        lblRecieverName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecieverName.setForeground(new java.awt.Color(51, 0, 102));
        lblRecieverName.setText("Reciever Name:");
        panelprint.add(lblRecieverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, 30));

        txtrecieptno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtrecieptno.setForeground(new java.awt.Color(51, 0, 102));
        txtrecieptno.setText("Reciept No");
        panelprint.add(txtrecieptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 116, -1, 20));

        txtModeOP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtModeOP.setForeground(new java.awt.Color(51, 0, 102));
        txtModeOP.setText("Mode of Payment");
        panelprint.add(txtModeOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 20));

        txtcheque_dd_upi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcheque_dd_upi.setForeground(new java.awt.Color(51, 0, 102));
        txtcheque_dd_upi.setText("Cheque_dd_upi");
        panelprint.add(txtcheque_dd_upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 102));
        jLabel15.setText("Date:");
        panelprint.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 110, 40, 20));

        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdate.setForeground(new java.awt.Color(51, 0, 102));
        txtdate.setText("Date");
        panelprint.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 100, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 102));
        jLabel17.setText("GSTIN NO:");
        panelprint.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 70, 20));

        txtgstin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtgstin.setForeground(new java.awt.Color(51, 0, 102));
        txtgstin.setText("AWC568C7R5");
        panelprint.add(txtgstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 90, 20));

        txtyr1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtyr1.setForeground(new java.awt.Color(51, 0, 102));
        txtyr1.setText("2022");
        panelprint.add(txtyr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 102));
        jLabel13.setText("The following payment in the college office for the year:");
        panelprint.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 350, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("to");
        panelprint.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        txtyr2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtyr2.setForeground(new java.awt.Color(51, 0, 102));
        txtyr2.setText("2025");
        panelprint.add(txtyr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 20));

        txtBankName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBankName.setForeground(new java.awt.Color(51, 0, 102));
        txtBankName.setText("Bank Name");
        panelprint.add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 236, 80, 20));

        txtRecieverName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecieverName.setForeground(new java.awt.Color(51, 0, 102));
        txtRecieverName.setText("Reciever Name");
        panelprint.add(txtRecieverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 276, 100, 20));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 102));
        panelprint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 343, 720, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 102));
        panelprint.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 720, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("Sr.No.");
        panelprint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("Heading");
        panelprint.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 102));
        jLabel12.setText("Amount (rs)");
        panelprint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        txtsrNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsrNo.setText("1");
        panelprint.add(txtsrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 40, -1));

        txtCourseName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCourseName.setForeground(new java.awt.Color(51, 0, 102));
        txtCourseName.setText("Course Name");
        panelprint.add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 20));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(51, 0, 102));
        txtAmount.setText("Amount");
        panelprint.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 100, 30));

        txtcgst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcgst.setForeground(new java.awt.Color(51, 0, 102));
        txtcgst.setText("CGST");
        panelprint.add(txtcgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 80, 30));

        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("CGST 7%");
        panelprint.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 456, -1, 20));

        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setText("SGST 7%");
        panelprint.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 496, -1, 20));

        txtsgst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsgst.setText("SGST");
        panelprint.add(txtsgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 70, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 51, 0));
        panelprint.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 180, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(51, 0, 102));
        txtTotal.setText("Total");
        panelprint.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 546, 90, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setText("Total in words:");
        panelprint.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 90, 20));

        txtTotalWords.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalWords.setForeground(new java.awt.Color(51, 0, 102));
        txtTotalWords.setText("Total in words");
        panelprint.add(txtTotalWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 290, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 102));
        jLabel22.setText("Remark:");
        panelprint.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 50, 20));

        jSeparator4.setForeground(new java.awt.Color(255, 51, 51));
        panelprint.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 180, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 102));
        jLabel23.setText("Reciever Signature");
        panelprint.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 120, 30));

        txtRemark.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRemark.setForeground(new java.awt.Color(51, 0, 102));
        txtRemark.setText("Remark");
        panelprint.add(txtRemark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 210, 20));

        getContentPane().add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 720, 680));

        setSize(new java.awt.Dimension(1014, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
        Color clr = new Color(0,153,153);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
        Color clr = new Color(0,51,51);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_lbllogoutMouseExited

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhomeMouseClicked

    private void lblhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseEntered
        Color clr = new Color(0,153,153);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_lblhomeMouseEntered

    private void lblhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseExited
        Color clr = new Color(0,51,51);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_lblhomeMouseExited

    private void lblsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseEntered
        Color clr = new Color(0,153,153);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_lblsearchMouseEntered

    private void lblsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseExited
        Color clr = new Color(0,51,51);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_lblsearchMouseExited

    private void lbleditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseEntered
        Color clr = new Color(0,153,153);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_lbleditCourseMouseEntered

    private void lbleditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseExited
        Color clr = new Color(0,51,51);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_lbleditCourseMouseExited

    private void lblcourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcourseListMouseEntered
        Color clr = new Color(0,153,153);
        courselistpanel.setBackground(clr);
    }//GEN-LAST:event_lblcourseListMouseEntered

    private void lblcourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcourseListMouseExited
        Color clr = new Color(0,51,51);
        courselistpanel.setBackground(clr);
    }//GEN-LAST:event_lblcourseListMouseExited

    private void lblbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseEntered
        Color clr = new Color(0,153,153);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_lblbackMouseEntered

    private void lblbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseExited
        Color clr = new Color(0,51,51);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_lblbackMouseExited

    private void btnprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseEntered
        Color clr = new Color(0,153,153);
       printpanel.setBackground(clr);
    }//GEN-LAST:event_btnprintMouseEntered

    private void btnprintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseExited
         Color clr = new Color(0,51,51);
          printpanel.setBackground(clr);
    }//GEN-LAST:event_btnprintMouseExited

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
          Color clr = new Color(0,153,153);
       editpanel.setBackground(clr);
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
      Color clr = new Color(0,51,51);
       editpanel.setBackground(clr);
    }//GEN-LAST:event_btneditMouseExited

    private void btnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseClicked
       PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
               panelprint.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btnprintMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
       UpdateFeesDetail ufd = new UpdateFeesDetail();
       ufd.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btneditMouseClicked

    private void lblsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseClicked
       SearchRecord sr = new SearchRecord();
       sr.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblsearchMouseClicked

    private void lbleditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseClicked
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbleditCourseMouseClicked

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
         SignUp su = new SignUp();
       su.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lblcourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcourseListMouseClicked
      ViewAllRecord var = new ViewAllRecord();
      var.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_lblcourseListMouseClicked

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
       AddFees af = new AddFees();
       af.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanel;
    private javax.swing.JLabel btnedit;
    private javax.swing.JLabel btnprint;
    private javax.swing.JPanel courselistpanel;
    private javax.swing.JPanel editcoursepanel;
    private javax.swing.JPanel editpanel;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblModeOP;
    private javax.swing.JLabel lblRecieptNo;
    private javax.swing.JLabel lblRecieverName;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblcheque_dd_upi;
    private javax.swing.JLabel lblcourseList;
    private javax.swing.JLabel lbleditCourse;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JPanel logoutpanel;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panelprint;
    private javax.swing.JPanel printpanel;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JLabel txtAmount;
    private javax.swing.JLabel txtBankName;
    private javax.swing.JLabel txtCourseName;
    private javax.swing.JLabel txtModeOP;
    private javax.swing.JLabel txtRecieverName;
    private javax.swing.JLabel txtRemark;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTotalWords;
    private javax.swing.JLabel txtcgst;
    private javax.swing.JLabel txtcheque_dd_upi;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txtgstin;
    private javax.swing.JLabel txtrecieptno;
    private javax.swing.JLabel txtsgst;
    private javax.swing.JLabel txtsrNo;
    private javax.swing.JLabel txtyr1;
    private javax.swing.JLabel txtyr2;
    // End of variables declaration//GEN-END:variables
}
