/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSignup = new javax.swing.JLabel();
        signupImg = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        lblFirstname = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        date_choose = new com.toedter.calendar.JDateChooser();
        lblDob = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        txtConfirmpass = new javax.swing.JPasswordField();
        btnsignup = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnclearSign = new javax.swing.JButton();
        lblPassError = new javax.swing.JLabel();
        lblConfirmPassError = new javax.swing.JLabel();
        lblContactError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignup.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSignup.setForeground(new java.awt.Color(255, 255, 255));
        lblSignup.setText("Signup");
        jPanel1.add(lblSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 130, 59));

        signupImg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signupImg.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\signup.png")); // NOI18N
        jPanel1.add(signupImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 40, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        panel1.setBackground(new java.awt.Color(0, 153, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("Firstname");
        panel1.add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, 30));

        lblLastname.setBackground(new java.awt.Color(255, 255, 255));
        lblLastname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("Lastname :");
        panel1.add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 30));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username :");
        panel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password :");
        panel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 30));

        lblConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setText("Confirm Password :");
        panel1.add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 170, 30));

        txtLname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        panel1.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 200, -1));

        txtFname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        panel1.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 200, -1));

        txtUname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panel1.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 160, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        panel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 160, -1));
        panel1.add(date_choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 160, -1));

        lblDob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDob.setForeground(new java.awt.Color(255, 255, 255));
        lblDob.setText("D.O.B . ");
        panel1.add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 70, 20));

        lblContactNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContactNo.setForeground(new java.awt.Color(255, 255, 255));
        lblContactNo.setText("Contact Number :");
        panel1.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 160, -1));

        txtContactNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });
        panel1.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 140, -1));

        txtConfirmpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtConfirmpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmpassKeyTyped(evt);
            }
        });
        panel1.add(txtConfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 160, -1));

        btnsignup.setBackground(new java.awt.Color(0, 51, 51));
        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\signup.png")); // NOI18N
        btnsignup.setText("Signup");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        panel1.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        btnlogin.setBackground(new java.awt.Color(0, 51, 51));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\login.png")); // NOI18N
        btnlogin.setText("Login ");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        panel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        btnclearSign.setBackground(new java.awt.Color(0, 51, 51));
        btnclearSign.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclearSign.setForeground(new java.awt.Color(255, 255, 255));
        btnclearSign.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\exit.png")); // NOI18N
        btnclearSign.setText("Clear");
        btnclearSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearSignActionPerformed(evt);
            }
        });
        panel1.add(btnclearSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 100, 30));

        lblPassError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassError.setForeground(new java.awt.Color(255, 0, 0));
        panel1.add(lblPassError, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 300, 30));

        lblConfirmPassError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConfirmPassError.setForeground(new java.awt.Color(255, 51, 0));
        panel1.add(lblConfirmPassError, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 330, 30));

        lblContactError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContactError.setForeground(new java.awt.Color(255, 0, 0));
        panel1.add(lblContactError, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 376, 260, 30));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void btnclearSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearSignActionPerformed
            
          txtFname.setText("");
          txtLname.setText("");
          txtUname.setText("");
          txtPassword.setText("");
          txtConfirmpass.setText("");
          date_choose.setDate(null);
          txtContactNo.setText("");
        
    }//GEN-LAST:event_btnclearSignActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
       
        
   if(validation()){
            insertData();
        }
        
    
    }//GEN-LAST:event_btnsignupActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        passwordCheck();
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        passwordCheck();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
       passwordCheck();
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtContactNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyPressed
       contactCheck();
    }//GEN-LAST:event_txtContactNoKeyPressed

    private void txtContactNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyReleased
        contactCheck();
    }//GEN-LAST:event_txtContactNoKeyReleased

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
        contactCheck();
    }//GEN-LAST:event_txtContactNoKeyTyped

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
      
        Login l1 = new Login();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtConfirmpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmpassKeyPressed
       conpasswordCheck();
    }//GEN-LAST:event_txtConfirmpassKeyPressed

    private void txtConfirmpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmpassKeyReleased
        conpasswordCheck();
    }//GEN-LAST:event_txtConfirmpassKeyReleased

    private void txtConfirmpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmpassKeyTyped
          conpasswordCheck();
    }//GEN-LAST:event_txtConfirmpassKeyTyped
    String fname, lname, uname, passwd, conpasswd, contactnm;
    Date dob;
    
    int id = 0;
    int getId(){
        ResultSet rs = null;
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            String sql = "select max(id) from signup";
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);
            
          while(rs.next()){
             
             id = rs.getInt(1);
             id++; 
          }
        }
        catch(Exception e){
            e.printStackTrace();
        } 
         return id;
    }
    
    void insertData(){
        
        SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
        String dob1 = s1.format(date_choose.getDate());
        try
        {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            
            String sql = "insert into signup values(?,?,?,?,?,?,?)";
            PreparedStatement st = con.prepareStatement(sql);
            
            st.setInt(1,getId());
            st.setString(2, fname);
            st.setString(3,lname);
            st.setString(4,uname);
            st.setString(5,passwd);
            st.setString(6,dob1);
            st.setString(7,contactnm);
            int i = st.executeUpdate();
            if(i > 0){
                
                JOptionPane.showMessageDialog(this,"Record Inserted Successfully");
            }
            else{
                
                JOptionPane.showMessageDialog(this,"Record Not Inserted Successfully");
            }
        }
        catch(Exception e){
            
             e.printStackTrace();
        }
            
    }
    
    boolean validation(){
        
       fname = txtFname.getText();
       lname = txtLname.getText();
       uname = txtUname.getText();
       passwd = txtPassword.getText();
       conpasswd = txtConfirmpass.getText();
       dob = date_choose.getDate();
       contactnm = txtContactNo.getText();
       
       if(fname.equals("")){
           
           JOptionPane.showMessageDialog(this,"Please, Enter Firstname.");
           return false;
       }
       
        if(lname.equals("")){
           
           JOptionPane.showMessageDialog(this,"Please, Enter Lastname.");
           return false;
       }
        
         if(uname.equals("")){
           
           JOptionPane.showMessageDialog(this,"Please, Enter Username.");
           return false;
       }
       
        if(passwd.equals("")){
           
           JOptionPane.showMessageDialog(this,"Please, Enter Password.");
           return false;
       }
          
        if(conpasswd.equals("")){
           
           JOptionPane.showMessageDialog(this,"Please, Enter again Confirm Password!");
           return false;
       }
           
         if(dob == null){
           
           JOptionPane.showMessageDialog(this,"Please, Enter Date of Birth.");
           return false;
       }
            
         if(contactnm.equals("")){
           
           JOptionPane.showMessageDialog(this,"Please, Enter Contact Number.");
           return false;
       }
         if(!passwd.equals(conpasswd)){
             JOptionPane.showMessageDialog(this,"Password not matched");
             return false;
         }
        return true;           
    }
    
    void  passwordCheck(){
         passwd = txtPassword.getText();
         if(passwd.length() >= 8){
              lblPassError.setText("");
       }    
         else{
             lblPassError.setText("Password should be 8 digits.");
         }
    }
    
     void  conpasswordCheck(){
       conpasswd = txtConfirmpass.getText();
         if(  conpasswd.length() >= 8){
             lblConfirmPassError.setText("");
       }    
         else{
              lblConfirmPassError.setText("Please, Again Enter Confirm Password.");
         }
    }
    
    
    
    void contactCheck(){
        contactnm = txtContactNo.getText();
        if(contactnm.length() == 10){
             lblContactError.setText("");
        }
        else{
              lblContactError.setText("Contact No should be of 10 digits.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclearSign;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private com.toedter.calendar.JDateChooser date_choose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmPassError;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblContactError;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblPassError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblUsername;
    private java.awt.Panel panel1;
    private javax.swing.JLabel signupImg;
    private javax.swing.JPasswordField txtConfirmpass;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
