/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ViewAllRecord extends javax.swing.JFrame {
    
    /**
     * Creates new form ViewAllRecord
     */
    public ViewAllRecord() {
        initComponents();
        viewRecordsTable();
    }
     DefaultTableModel model;
     
     public void viewRecordsTable(){
         try{
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            String sql = "select * from fees_details";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String recieptNo = rs.getString("reciept_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("course_name");
                String paymentMode = rs.getString("payment_mode");
                float totalAmount = rs.getFloat("total_amount");
                String date = rs.getString("date");
                String remark = rs.getString("remark");
                
                Object[] obj = {recieptNo,rollNo, studentName, courseName,paymentMode,totalAmount,date,remark  };
                model = (DefaultTableModel)viewRecordTable.getModel();
                model.addRow(obj);
               
         
            
          }
       
         }  
        
        catch(Exception e){
            
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        logoutpanel = new javax.swing.JPanel();
        lbllogout = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        lblsearch = new javax.swing.JLabel();
        editcoursepanel = new javax.swing.JPanel();
        lbleditCourse = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        lblback = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewRecordTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 51, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutpanel.setBackground(new java.awt.Color(0, 51, 51));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\exit.png")); // NOI18N
        lbllogout.setText("Logout");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });
        logoutpanel.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        panel1.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 120, 40));

        homepanel.setBackground(new java.awt.Color(0, 51, 51));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblhome.setForeground(new java.awt.Color(255, 255, 255));
        lblhome.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\home.png")); // NOI18N
        lblhome.setText("Home");
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhomeMouseExited(evt);
            }
        });
        homepanel.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        panel1.add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 60));

        searchpanel.setBackground(new java.awt.Color(0, 51, 51));
        searchpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsearch.setForeground(new java.awt.Color(255, 255, 255));
        lblsearch.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\search2.png")); // NOI18N
        lblsearch.setText("Search Record");
        lblsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsearchMouseExited(evt);
            }
        });
        searchpanel.add(lblsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        panel1.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 70));

        editcoursepanel.setBackground(new java.awt.Color(0, 51, 51));
        editcoursepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        editcoursepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbleditCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbleditCourse.setForeground(new java.awt.Color(255, 255, 255));
        lbleditCourse.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\edit2.png")); // NOI18N
        lbleditCourse.setText("Edit Course");
        lbleditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseExited(evt);
            }
        });
        editcoursepanel.add(lbleditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.add(editcoursepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, -1));

        backpanel.setBackground(new java.awt.Color(0, 51, 51));
        backpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        backpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblback.setForeground(new java.awt.Color(255, 255, 255));
        lblback.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\back1.png")); // NOI18N
        lblback.setText("Back");
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbackMouseExited(evt);
            }
        });
        backpanel.add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        panel1.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 630));

        panel2.setBackground(new java.awt.Color(0, 153, 153));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reciept No", "Roll No", "Student Name", "Course Name", "Total Amount", "Payment Mode", "Date", "Remark"
            }
        ));
        jScrollPane2.setViewportView(viewRecordTable);

        panel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 920, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View All Record");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 190, 30));
        panel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 33, -1, 20));
        panel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 200, -1));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 950, 630));

        setSize(new java.awt.Dimension(1252, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
        Color clr = new Color(0,153,153);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
        Color clr = new Color(0,51,51);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_lbllogoutMouseExited

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhomeMouseClicked

    private void lblhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseEntered
        Color clr = new Color(0,153,153);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_lblhomeMouseEntered

    private void lblhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseExited
        Color clr = new Color(0,51,51);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_lblhomeMouseExited

    private void lblsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblsearchMouseClicked

    private void lblsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseEntered
        Color clr = new Color(0,153,153);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_lblsearchMouseEntered

    private void lblsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseExited
        Color clr = new Color(0,51,51);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_lblsearchMouseExited

    private void lbleditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseEntered
        Color clr = new Color(0,153,153);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_lbleditCourseMouseEntered

    private void lbleditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseExited
        Color clr = new Color(0,51,51);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_lbleditCourseMouseExited

    private void lblbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseEntered
        Color clr = new Color(0,153,153);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_lblbackMouseEntered

    private void lblbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseExited
        Color clr = new Color(0,51,51);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_lblbackMouseExited

    private void lbleditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseClicked
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbleditCourseMouseClicked

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblbackMouseClicked

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        SignUp su = new SignUp();
       su.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbllogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanel;
    private javax.swing.JPanel editcoursepanel;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lbleditCourse;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JPanel logoutpanel;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JTable viewRecordTable;
    // End of variables declaration//GEN-END:variables
}
