/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import com.mycompany.fees_management_system.AddFees.NumberToWordsConverter;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ViewReport extends javax.swing.JFrame {

    /**
     * Creates new form ViewReport
     */
    public ViewReport() {
        initComponents();
        fillComboBox();
    }
    
    
      DefaultTableModel model;
     public void setCourseTable(){
            String cname = comboCourseView.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String fromDate = sdf.format(fromDateC.getDate());
        String toDate = sdf.format(toDateC.getDate());
        Float totalamt = 0.0f;
         
     try{
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            
            PreparedStatement st = con.prepareStatement("select * from fees_details where date between ? and ? and course_name = ?");
            st.setString(1,fromDate);
            st.setString(2, toDate);
            st.setString(3,cname);
            
            ResultSet rs = st.executeQuery();
            while(rs.next()){
                String recieptNo= rs.getString("reciept_no");
                String rollNo = rs.getString("roll_no");
                String studentName = rs.getString("student_name");
                String courseName = rs.getString("course_name");
                Float totalAmt = Float.parseFloat(rs.getString("total_amount"));
                String remark = rs.getString("remark");
                
                totalamt = totalamt + totalAmt;
                
               
                
                Object[] obj = {recieptNo,rollNo,studentName,courseName,totalAmt,remark};
                model = (DefaultTableModel)viewReportTable.getModel();
                model.addRow(obj);
               
         
          }   txtcourseSelect.setText(cname);
              txttotalamt.setText(totalamt.toString());
              txttotalamtW.setText(NumberToWordsConverter.convert(totalamt.intValue()));
         }  
        
        catch(Exception e){
            
            e.printStackTrace();
        }
    }
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel)viewReportTable.getModel();
        model.setRowCount(0);
    }
     public void fillComboBox(){
      
        try{
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/fees_managementsystemdb";
            Connection con =  DriverManager.getConnection(url,"root","Khalid@123");
            String sql = "select cname from course";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
             
           comboCourseView.addItem(rs.getString("cname"));
            
          }
       
           
        }
        catch(Exception e){
            
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        logoutpanel = new javax.swing.JPanel();
        lbllogout = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        lblsearch = new javax.swing.JLabel();
        editcoursepanel = new javax.swing.JPanel();
        lbleditCourse = new javax.swing.JLabel();
        courselistpanel = new javax.swing.JPanel();
        lblcourseList = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        lblback = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        lblselectCourse = new javax.swing.JLabel();
        comboCourseView = new javax.swing.JComboBox<>();
        lblselectDate = new javax.swing.JLabel();
        lblfromDate = new javax.swing.JLabel();
        fromDateC = new com.toedter.calendar.JDateChooser();
        lblToDate = new javax.swing.JLabel();
        toDateC = new com.toedter.calendar.JDateChooser();
        btnSubmit = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewReportTable = new javax.swing.JTable();
        panel3 = new java.awt.Panel();
        courseSelected = new javax.swing.JLabel();
        lblTotalamt = new javax.swing.JLabel();
        lbltotalamtw = new javax.swing.JLabel();
        txtcourseSelect = new javax.swing.JLabel();
        txttotalamt = new javax.swing.JLabel();
        txttotalamtW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 51, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutpanel.setBackground(new java.awt.Color(0, 51, 51));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\exit.png")); // NOI18N
        lbllogout.setText("Logout");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });
        logoutpanel.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        panel1.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 120, 40));

        homepanel.setBackground(new java.awt.Color(0, 51, 51));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblhome.setForeground(new java.awt.Color(255, 255, 255));
        lblhome.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\home.png")); // NOI18N
        lblhome.setText("Home");
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhomeMouseExited(evt);
            }
        });
        homepanel.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        panel1.add(homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 160, 60));

        searchpanel.setBackground(new java.awt.Color(0, 51, 51));
        searchpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsearch.setForeground(new java.awt.Color(255, 255, 255));
        lblsearch.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\search2.png")); // NOI18N
        lblsearch.setText("Search Record");
        lblsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsearchMouseExited(evt);
            }
        });
        searchpanel.add(lblsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        panel1.add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 70));

        editcoursepanel.setBackground(new java.awt.Color(0, 51, 51));
        editcoursepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        editcoursepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbleditCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbleditCourse.setForeground(new java.awt.Color(255, 255, 255));
        lbleditCourse.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\edit2.png")); // NOI18N
        lbleditCourse.setText("Edit Course");
        lbleditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbleditCourseMouseExited(evt);
            }
        });
        editcoursepanel.add(lbleditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.add(editcoursepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, -1));

        courselistpanel.setBackground(new java.awt.Color(0, 51, 51));
        courselistpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        courselistpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcourseList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcourseList.setForeground(new java.awt.Color(255, 255, 255));
        lblcourseList.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\view all record_1.png")); // NOI18N
        lblcourseList.setText("View Record");
        lblcourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcourseListMouseExited(evt);
            }
        });
        courselistpanel.add(lblcourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        panel1.add(courselistpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 170, 70));

        backpanel.setBackground(new java.awt.Color(0, 51, 51));
        backpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        backpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblback.setForeground(new java.awt.Color(255, 255, 255));
        lblback.setIcon(new javax.swing.ImageIcon("E:\\Project\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\my icons\\back1.png")); // NOI18N
        lblback.setText("Back");
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbackMouseExited(evt);
            }
        });
        backpanel.add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        panel1.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 120, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 630));

        panel2.setBackground(new java.awt.Color(0, 153, 153));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblselectCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblselectCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblselectCourse.setText("Select Course:");
        panel2.add(lblselectCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, -1));

        comboCourseView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseViewActionPerformed(evt);
            }
        });
        panel2.add(comboCourseView, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 350, 30));

        lblselectDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblselectDate.setForeground(new java.awt.Color(255, 255, 255));
        lblselectDate.setText("Select Date:");
        panel2.add(lblselectDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 30));

        lblfromDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblfromDate.setForeground(new java.awt.Color(255, 255, 255));
        lblfromDate.setText("From Date");
        panel2.add(lblfromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, 20));
        panel2.add(fromDateC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 120, -1));

        lblToDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToDate.setForeground(new java.awt.Color(255, 255, 255));
        lblToDate.setText("To Date");
        panel2.add(lblToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 70, 30));
        panel2.add(toDateC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, -1));

        btnSubmit.setBackground(new java.awt.Color(0, 51, 51));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        panel2.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        btnPrint.setBackground(new java.awt.Color(0, 51, 51));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        panel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 30));

        viewReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reciept No", "Roll No", "Student Name", "Course Name", "Total Amout", "Remark"
            }
        ));
        jScrollPane1.setViewportView(viewReportTable);

        panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 930, 380));

        panel3.setBackground(new java.awt.Color(0, 204, 204));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseSelected.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseSelected.setForeground(new java.awt.Color(255, 255, 255));
        courseSelected.setText("Course Selected:");
        panel3.add(courseSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        lblTotalamt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalamt.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalamt.setText("Total Amount:");
        panel3.add(lblTotalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        lbltotalamtw.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalamtw.setText("Total Amount in Words:");
        panel3.add(lbltotalamtw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 30));
        panel3.add(txtcourseSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 200, 20));
        panel3.add(txttotalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 46, 230, 30));
        panel3.add(txttotalamtW, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 126, 300, 30));

        panel2.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 350, 160));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 970, 630));

        setSize(new java.awt.Dimension(1274, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
        Color clr = new Color(0,153,153);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
        Color clr = new Color(0,51,51);
        logoutpanel.setBackground(clr);
    }//GEN-LAST:event_lbllogoutMouseExited

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhomeMouseClicked

    private void lblhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseEntered
        Color clr = new Color(0,153,153);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_lblhomeMouseEntered

    private void lblhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseExited
        Color clr = new Color(0,51,51);
        homepanel.setBackground(clr);
    }//GEN-LAST:event_lblhomeMouseExited

    private void lblsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseClicked
        SearchRecord sr = new SearchRecord();
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblsearchMouseClicked

    private void lblsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseEntered
        Color clr = new Color(0,153,153);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_lblsearchMouseEntered

    private void lblsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseExited
        Color clr = new Color(0,51,51);
        searchpanel.setBackground(clr);
    }//GEN-LAST:event_lblsearchMouseExited

    private void lbleditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseClicked
        EditCourse ec = new EditCourse();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbleditCourseMouseClicked

    private void lbleditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseEntered
        Color clr = new Color(0,153,153);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_lbleditCourseMouseEntered

    private void lbleditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbleditCourseMouseExited
        Color clr = new Color(0,51,51);
        editcoursepanel.setBackground(clr);
    }//GEN-LAST:event_lbleditCourseMouseExited

    private void lblcourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcourseListMouseEntered
        Color clr = new Color(0,153,153);
        courselistpanel.setBackground(clr);
    }//GEN-LAST:event_lblcourseListMouseEntered

    private void lblcourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcourseListMouseExited
        Color clr = new Color(0,51,51);
        courselistpanel.setBackground(clr);
    }//GEN-LAST:event_lblcourseListMouseExited

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblbackMouseClicked

    private void lblbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseEntered
        Color clr = new Color(0,153,153);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_lblbackMouseEntered

    private void lblbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseExited
        Color clr = new Color(0,51,51);
        backpanel.setBackground(clr);
    }//GEN-LAST:event_lblbackMouseExited

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        Color clr = new Color(0,153,153);
        btnSubmit.setBackground(clr);
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        Color clr = new Color(0,51,51);
        btnSubmit.setBackground(clr);
    }//GEN-LAST:event_btnSubmitMouseExited

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
         Color clr = new Color(0,153,153);
        btnPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        Color clr = new Color(0,51,51);
        btnPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseExited

    private void comboCourseViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCourseViewActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
          PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
               viewReportTable.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        clearTable();
        setCourseTable();
      
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        SignUp su = new SignUp();
       su.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lblcourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcourseListMouseClicked
        ViewAllRecord var = new ViewAllRecord();
        var.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblcourseListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backpanel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboCourseView;
    private javax.swing.JLabel courseSelected;
    private javax.swing.JPanel courselistpanel;
    private javax.swing.JPanel editcoursepanel;
    private com.toedter.calendar.JDateChooser fromDateC;
    private javax.swing.JPanel homepanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblToDate;
    private javax.swing.JLabel lblTotalamt;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblcourseList;
    private javax.swing.JLabel lbleditCourse;
    private javax.swing.JLabel lblfromDate;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JLabel lblselectCourse;
    private javax.swing.JLabel lblselectDate;
    private javax.swing.JLabel lbltotalamtw;
    private javax.swing.JPanel logoutpanel;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JPanel searchpanel;
    private com.toedter.calendar.JDateChooser toDateC;
    private javax.swing.JLabel txtcourseSelect;
    private javax.swing.JLabel txttotalamt;
    private javax.swing.JLabel txttotalamtW;
    private javax.swing.JTable viewReportTable;
    // End of variables declaration//GEN-END:variables
}
